# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name : checkout main from branch
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Step 2 - set up jdk 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          cache: maven
          
      # 
      - name: step 3 run maven
        run: mvn -B package --file app/pom.xml
        
      - name: step 4 show resultat
        run: ls -a
        
      - name: step 5 run test
        run: mvn -f app/pom.xml test
        

      #Generation de coverage code avec jacoco
      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: app/target/site/jacoco/jacoco.csv
          badges-directory: .github/badges
      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name: Commit the badge (if it changed)
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'YoussefElkasri'
            git config --global user.email 'elkasri.youssef@outlook.fr'
            git add -A
            git commit -m "Autogenerated JaCoCo coverage badge"
            git push origin main
          fi

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: app/target/site/jacoco/
          

      #connecting to docker hub  
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
          
      - name: docker build image
        run: |
          docker build -t 19982001/dataframe_2022 .
      - name: docker push
        run: |
          docker push 19982001/dataframe_2022
